version: "3.3"

services:
  nginx:
    build:
      context: docker/development
      dockerfile: nginx/Dockerfile
    environment:
      SERVER_NAME: ${DOMAIN_NAME}
    ports:
      - "80:80"
      - "443:443"
    networks:
      - net_universa
    volumes:
      - /var/www/universa-core:/app/app-backend
      - ./log:/var/log/nginx/:rw
    depends_on:
      - php-fpm

  php-fpm:
    build:
      args:
          user: ${USER_NAME}
          uid: ${USER_PID}
      context: docker/development
      dockerfile: php-fpm/Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - XDEBUG_MODE=develop,debug
    networks:
      - net_universa
    volumes:
      - /var/www/universa-core:/app/app-backend
      - ./log:/var/log:rw
    
    expose:
      - 9003

  php-cli:
    build:
      context: docker/development
      dockerfile: php-cli/Dockerfile
    networks:
      - net_universa
    volumes:
      - /var/www/universa-core:/app/app-backend
      - ./log:/var/log/:rw

  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    networks:
      - net_universa
    volumes:
      - ./var/database:/var/lib/mysql:rw

networks:
  net_universa:
    driver: bridge