version: "3.3"

networks:
  net_app:
    driver: bridge

services:
  nginx:
    build:
      context: docker/development
      dockerfile: nginx/Dockerfile
    environment:
      SERVER_NAME: ${DOMAIN_NAME}
    ports:
      - "${NGINX_HOST_HTTP_PORT:-80}:80"
      - "${NGINX_HOST_HTTPS_PORT:-443}:443"
    networks:
      - net_app
    volumes:
      - /var/www/src:/var/www
      - ./log:/var/log/nginx/:rw
    depends_on:
      - php
    links:
      - php

  php:
    build:
      args:
          user: ${USER_NAME}
          uid: ${USER_PID}
          PHP_VERSION: ${PHP_VERSION}
          INSTALL_COMPRESSION: ${PHP_FPM_INSTALL_COMPRESSION}
          INSTALL_PDO_POSTGRESQL: ${PHP_FPM_INSTALL_PDO_POSTGRESQL}
          INSTALL_BCMATH: ${PHP_FPM_INSTALL_BCMATH}
          INSTALL_XDEBUG: ${PHP_FPM_INSTALL_XDEBUG}
          INSTALL_COMPOSER: ${PHP_FPM_INSTALL_COMPOSER}
          INSTALL_SWOOLE: ${PHP_FPM_INSTALL_SWOOLE}
          INSTALL_REDIS: ${PHP_FPM_INSTALL_REDIS}
          INSTALL_IMAGICK: ${PHP_FPM_INSTALL_IMAGICK}
          INSTALL_DEV: ${PHP_FPM_INSTALL_DEV}
          WORKING_DIR: /var/www
      context: docker/development
      dockerfile: php-fpm/Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      XDEBUG_MODE: develop,debug,trace
      XDEBUG_CONFIG:
        client_host=host.docker.internal
        start_with_request=yes
    networks:
      - net_app
    volumes:
      - /var/www/src:/var/www
      - ./log:/var/log:rw
    
    expose:
      - 9003

  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    networks:
      - net_app
    volumes:
      - ./var/database:/var/lib/mysql:rw

